local scale = 1.8;

local fontHeight = math.floor(11 * scale);
local fontOutline, fontSize;
if (fontHeight < 10) then
    fontOutline = 1;
    fontSize = (fontHeight - 1);
else
    fontOutline = 2;
    fontSize = (fontHeight - 2);
end

local padding = math.floor(5 * scale);
local frame = math.floor(2 * scale);
local square = math.floor(40 * scale);
local spacing = math.floor(12 * scale);

local objWidth = square + (2 * (padding + frame));
local objHeight = square + (2 * frame) + fontHeight;

local verticalOffset1 = square;
local verticalOffset2 = verticalOffset1 + square + (2 * frame);
local panelHeight = verticalOffset2 + objHeight;

local theme = {};
theme.CrossPath = 'misc/cross.png';
theme.TriggerPath = 'misc/trigger.png';
theme.SkillchainAnimationPaths = T{};
theme.SkillchainAnimationPaths[1] = 'misc/crawl1.png';
theme.SkillchainAnimationPaths[2] = 'misc/crawl2.png';
theme.SkillchainAnimationPaths[3] = 'misc/crawl3.png';
theme.SkillchainAnimationPaths[4] = 'misc/crawl4.png';
theme.SkillchainAnimationPaths[5] = 'misc/crawl5.png';
theme.SkillchainAnimationPaths[6] = 'misc/crawl6.png';
theme.SkillchainAnimationPaths[7] = 'misc/crawl7.png';
theme.SkillchainAnimationTime = 0.08;
theme.IconFadeAlpha = 0.5;
theme.SingleDisplay1 = {};
theme.SingleDisplay1.FontObjects = {};
theme.SingleDisplay1.FontObjects.Cost = {};
theme.SingleDisplay1.FontObjects.Cost.BoxWidth = square;
theme.SingleDisplay1.FontObjects.Cost.BoxHeight = fontHeight;
theme.SingleDisplay1.FontObjects.Cost.OffsetX = padding + frame;
theme.SingleDisplay1.FontObjects.Cost.OffsetY = (frame + square) - fontHeight;
theme.SingleDisplay1.FontObjects.Cost.OutlineWidth = fontOutline;
theme.SingleDisplay1.FontObjects.Cost.FontHeight = fontSize;
theme.SingleDisplay1.FontObjects.Cost.FontFamily = 'Arial';
theme.SingleDisplay1.FontObjects.Cost.FontFlags = 0;
theme.SingleDisplay1.FontObjects.Cost.FontAlignment = 2;
theme.SingleDisplay1.FontObjects.Cost.FontColor = 0xFF389609;
theme.SingleDisplay1.FontObjects.Cost.OutlineColor = 0xFF000000;
theme.SingleDisplay1.FontObjects.Macro = {};
theme.SingleDisplay1.FontObjects.Macro.BoxWidth = square;
theme.SingleDisplay1.FontObjects.Macro.BoxHeight = fontHeight;
theme.SingleDisplay1.FontObjects.Macro.OffsetX = padding + frame;
theme.SingleDisplay1.FontObjects.Macro.OffsetY = frame;
theme.SingleDisplay1.FontObjects.Macro.OutlineWidth = fontOutline;
theme.SingleDisplay1.FontObjects.Macro.FontHeight = fontSize;
theme.SingleDisplay1.FontObjects.Macro.FontFamily = 'Arial';
theme.SingleDisplay1.FontObjects.Macro.FontFlags = 0;
theme.SingleDisplay1.FontObjects.Macro.FontAlignment = 0;
theme.SingleDisplay1.FontObjects.Macro.FontColor = 0xFFFFFFFF;
theme.SingleDisplay1.FontObjects.Macro.OutlineColor = 0xFF000000;
theme.SingleDisplay1.FontObjects.Name = {};
theme.SingleDisplay1.FontObjects.Name.BoxWidth = square + ((padding + frame) * 2);
theme.SingleDisplay1.FontObjects.Name.BoxHeight = fontHeight;
theme.SingleDisplay1.FontObjects.Name.OffsetX = 0;
theme.SingleDisplay1.FontObjects.Name.OffsetY = (2 * frame) + square;
theme.SingleDisplay1.FontObjects.Name.OutlineWidth = fontOutline;
theme.SingleDisplay1.FontObjects.Name.FontHeight = fontSize;
theme.SingleDisplay1.FontObjects.Name.FontFamily = 'Arial';
theme.SingleDisplay1.FontObjects.Name.FontFlags = 0;
theme.SingleDisplay1.FontObjects.Name.FontAlignment = 1;
theme.SingleDisplay1.FontObjects.Name.FontColor = 0xFFFFFFFF;
theme.SingleDisplay1.FontObjects.Name.OutlineColor = 0xFF000000;
theme.SingleDisplay1.FontObjects.Recast = {};
theme.SingleDisplay1.FontObjects.Recast.BoxWidth = square;
theme.SingleDisplay1.FontObjects.Recast.BoxHeight = fontHeight;
theme.SingleDisplay1.FontObjects.Recast.OffsetX = padding + frame;
theme.SingleDisplay1.FontObjects.Recast.OffsetY = (frame + square) - fontHeight;
theme.SingleDisplay1.FontObjects.Recast.OutlineWidth = fontOutline;
theme.SingleDisplay1.FontObjects.Recast.FontHeight = fontSize;
theme.SingleDisplay1.FontObjects.Recast.FontFamily = 'Arial';
theme.SingleDisplay1.FontObjects.Recast.FontFlags = 0;
theme.SingleDisplay1.FontObjects.Recast.FontAlignment = 0;
theme.SingleDisplay1.FontObjects.Recast.FontColor = 0xFF389609;
theme.SingleDisplay1.FontObjects.Recast.OutlineColor = 0xFF000000;
theme.SingleDisplay1.ImageObjects = {};
theme.SingleDisplay1.ImageObjects.Frame = {};
theme.SingleDisplay1.ImageObjects.Frame.OffsetX = padding;
theme.SingleDisplay1.ImageObjects.Frame.OffsetY = 0;
theme.SingleDisplay1.ImageObjects.Frame.Width = square + (2 * frame);
theme.SingleDisplay1.ImageObjects.Frame.Height = square + (2 * frame);
theme.SingleDisplay1.ImageObjects.Icon = {};
theme.SingleDisplay1.ImageObjects.Icon.OffsetX = padding + frame;
theme.SingleDisplay1.ImageObjects.Icon.OffsetY = frame;
theme.SingleDisplay1.ImageObjects.Icon.Width = square;
theme.SingleDisplay1.ImageObjects.Icon.Height = square;
theme.SingleDisplay1.ImageObjects.Overlay = {};
theme.SingleDisplay1.ImageObjects.Overlay.OffsetX = padding + frame;
theme.SingleDisplay1.ImageObjects.Overlay.OffsetY = frame;
theme.SingleDisplay1.ImageObjects.Overlay.Width = square;
theme.SingleDisplay1.ImageObjects.Overlay.Height = square;
theme.SingleDisplay1.Primitives = T{};
theme.SingleDisplay1.FramePath = 'misc/frame.png';
theme.SingleDisplay1.PanelHeight = panelHeight;
theme.SingleDisplay1.PanelWidth = (6 * objWidth) + 8 + spacing;
theme.SingleDisplay1.DefaultX = 0;
theme.SingleDisplay1.DefaultY = 0;
theme.SingleDisplay1.SquareHeight = objHeight;
theme.SingleDisplay1.SquareWidth = objWidth;
theme.SingleDisplay1.Squares = T{};
theme.SingleDisplay1.Squares[1] = { OffsetX = objWidth + 2, OffsetY = 0 };
theme.SingleDisplay1.Squares[2] = { OffsetX = (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.SingleDisplay1.Squares[3] = { OffsetX = objWidth + 2, OffsetY = verticalOffset2 };
theme.SingleDisplay1.Squares[4] = { OffsetX = 0, OffsetY = verticalOffset1 };
local offset = (objWidth * 3) + 4 + spacing;
theme.SingleDisplay1.Squares[5] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.SingleDisplay1.Squares[6] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.SingleDisplay1.Squares[7] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.SingleDisplay1.Squares[8] = { OffsetX = offset, OffsetY = verticalOffset1 };
theme.SingleDisplay2 = {};
theme.SingleDisplay2.FontObjects = {};
theme.SingleDisplay2.FontObjects.Cost = {};
theme.SingleDisplay2.FontObjects.Cost.BoxWidth = square;
theme.SingleDisplay2.FontObjects.Cost.BoxHeight = fontHeight;
theme.SingleDisplay2.FontObjects.Cost.OffsetX = padding + frame;
theme.SingleDisplay2.FontObjects.Cost.OffsetY = (frame + square) - fontHeight;
theme.SingleDisplay2.FontObjects.Cost.OutlineWidth = fontOutline;
theme.SingleDisplay2.FontObjects.Cost.FontHeight = fontSize;
theme.SingleDisplay2.FontObjects.Cost.FontFamily = 'Arial';
theme.SingleDisplay2.FontObjects.Cost.FontFlags = 0;
theme.SingleDisplay2.FontObjects.Cost.FontAlignment = 2;
theme.SingleDisplay2.FontObjects.Cost.FontColor = 0xFF389609;
theme.SingleDisplay2.FontObjects.Cost.OutlineColor = 0xFF000000;
theme.SingleDisplay2.FontObjects.Macro = {};
theme.SingleDisplay2.FontObjects.Macro.BoxWidth = square;
theme.SingleDisplay2.FontObjects.Macro.BoxHeight = fontHeight;
theme.SingleDisplay2.FontObjects.Macro.OffsetX = padding + frame;
theme.SingleDisplay2.FontObjects.Macro.OffsetY = frame;
theme.SingleDisplay2.FontObjects.Macro.OutlineWidth = fontOutline;
theme.SingleDisplay2.FontObjects.Macro.FontHeight = fontSize;
theme.SingleDisplay2.FontObjects.Macro.FontFamily = 'Arial';
theme.SingleDisplay2.FontObjects.Macro.FontFlags = 0;
theme.SingleDisplay2.FontObjects.Macro.FontAlignment = 0;
theme.SingleDisplay2.FontObjects.Macro.FontColor = 0xFFFFFFFF;
theme.SingleDisplay2.FontObjects.Macro.OutlineColor = 0xFF000000;
theme.SingleDisplay2.FontObjects.Name = {};
theme.SingleDisplay2.FontObjects.Name.BoxWidth = square + ((padding + frame) * 2);
theme.SingleDisplay2.FontObjects.Name.BoxHeight = fontHeight;
theme.SingleDisplay2.FontObjects.Name.OffsetX = 0;
theme.SingleDisplay2.FontObjects.Name.OffsetY = (2 * frame) + square;
theme.SingleDisplay2.FontObjects.Name.OutlineWidth = fontOutline;
theme.SingleDisplay2.FontObjects.Name.FontHeight = fontSize;
theme.SingleDisplay2.FontObjects.Name.FontFamily = 'Arial';
theme.SingleDisplay2.FontObjects.Name.FontFlags = 0;
theme.SingleDisplay2.FontObjects.Name.FontAlignment = 1;
theme.SingleDisplay2.FontObjects.Name.FontColor = 0xFFFFFFFF;
theme.SingleDisplay2.FontObjects.Name.OutlineColor = 0xFF000000;
theme.SingleDisplay2.FontObjects.Recast = {};
theme.SingleDisplay2.FontObjects.Recast.BoxWidth = square;
theme.SingleDisplay2.FontObjects.Recast.BoxHeight = fontHeight;
theme.SingleDisplay2.FontObjects.Recast.OffsetX = padding + frame;
theme.SingleDisplay2.FontObjects.Recast.OffsetY = (frame + square) - fontHeight;
theme.SingleDisplay2.FontObjects.Recast.OutlineWidth = fontOutline;
theme.SingleDisplay2.FontObjects.Recast.FontHeight = fontSize;
theme.SingleDisplay2.FontObjects.Recast.FontFamily = 'Arial';
theme.SingleDisplay2.FontObjects.Recast.FontFlags = 0;
theme.SingleDisplay2.FontObjects.Recast.FontAlignment = 0;
theme.SingleDisplay2.FontObjects.Recast.FontColor = 0xFF389609;
theme.SingleDisplay2.FontObjects.Recast.OutlineColor = 0xFF000000;
theme.SingleDisplay2.ImageObjects = {};
theme.SingleDisplay2.ImageObjects.Frame = {};
theme.SingleDisplay2.ImageObjects.Frame.OffsetX = padding;
theme.SingleDisplay2.ImageObjects.Frame.OffsetY = 0;
theme.SingleDisplay2.ImageObjects.Frame.Width = square + (2 * frame);
theme.SingleDisplay2.ImageObjects.Frame.Height = square + (2 * frame);
theme.SingleDisplay2.ImageObjects.Icon = {};
theme.SingleDisplay2.ImageObjects.Icon.OffsetX = padding + frame;
theme.SingleDisplay2.ImageObjects.Icon.OffsetY = frame;
theme.SingleDisplay2.ImageObjects.Icon.Width = square;
theme.SingleDisplay2.ImageObjects.Icon.Height = square;
theme.SingleDisplay2.ImageObjects.Overlay = {};
theme.SingleDisplay2.ImageObjects.Overlay.OffsetX = padding + frame;
theme.SingleDisplay2.ImageObjects.Overlay.OffsetY = frame;
theme.SingleDisplay2.ImageObjects.Overlay.Width = square;
theme.SingleDisplay2.ImageObjects.Overlay.Height = square;
theme.SingleDisplay2.Primitives = T{};
theme.SingleDisplay2.FramePath = 'misc/frame.png';
theme.SingleDisplay2.PanelHeight = panelHeight;
theme.SingleDisplay2.PanelWidth = (6 * objWidth) + 8 + spacing;
theme.SingleDisplay2.DefaultX = 0;
theme.SingleDisplay2.DefaultY = 0;
theme.SingleDisplay2.SquareHeight = objHeight;
theme.SingleDisplay2.SquareWidth = objWidth;
theme.SingleDisplay2.Squares = T{};
theme.SingleDisplay2.Squares[1] = { OffsetX = objWidth + 2, OffsetY = 0 };
theme.SingleDisplay2.Squares[2] = { OffsetX = (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.SingleDisplay2.Squares[3] = { OffsetX = objWidth + 2, OffsetY = verticalOffset2 };
theme.SingleDisplay2.Squares[4] = { OffsetX = 0, OffsetY = verticalOffset1 };
local offset = (objWidth * 3) + 4 + spacing;
theme.SingleDisplay2.Squares[5] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.SingleDisplay2.Squares[6] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.SingleDisplay2.Squares[7] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.SingleDisplay2.Squares[8] = { OffsetX = offset, OffsetY = verticalOffset1 };
theme.DoubleDisplay1 = {};
theme.DoubleDisplay1.FontObjects = {};
theme.DoubleDisplay1.FontObjects.Cost = {};
theme.DoubleDisplay1.FontObjects.Cost.BoxWidth = square;
theme.DoubleDisplay1.FontObjects.Cost.BoxHeight = fontHeight;
theme.DoubleDisplay1.FontObjects.Cost.OffsetX = padding + frame;
theme.DoubleDisplay1.FontObjects.Cost.OffsetY = (frame + square) - fontHeight;
theme.DoubleDisplay1.FontObjects.Cost.OutlineWidth = fontOutline;
theme.DoubleDisplay1.FontObjects.Cost.FontHeight = fontSize;
theme.DoubleDisplay1.FontObjects.Cost.FontFamily = 'Arial';
theme.DoubleDisplay1.FontObjects.Cost.FontFlags = 0;
theme.DoubleDisplay1.FontObjects.Cost.FontAlignment = 2;
theme.DoubleDisplay1.FontObjects.Cost.FontColor = 0xFF389609;
theme.DoubleDisplay1.FontObjects.Cost.OutlineColor = 0xFF000000;
theme.DoubleDisplay1.FontObjects.Macro = {};
theme.DoubleDisplay1.FontObjects.Macro.BoxWidth = square;
theme.DoubleDisplay1.FontObjects.Macro.BoxHeight = fontHeight;
theme.DoubleDisplay1.FontObjects.Macro.OffsetX = padding + frame;
theme.DoubleDisplay1.FontObjects.Macro.OffsetY = frame;
theme.DoubleDisplay1.FontObjects.Macro.OutlineWidth = fontOutline;
theme.DoubleDisplay1.FontObjects.Macro.FontHeight = fontSize;
theme.DoubleDisplay1.FontObjects.Macro.FontFamily = 'Arial';
theme.DoubleDisplay1.FontObjects.Macro.FontFlags = 0;
theme.DoubleDisplay1.FontObjects.Macro.FontAlignment = 0;
theme.DoubleDisplay1.FontObjects.Macro.FontColor = 0xFFFFFFFF;
theme.DoubleDisplay1.FontObjects.Macro.OutlineColor = 0xFF000000;
theme.DoubleDisplay1.FontObjects.Name = {};
theme.DoubleDisplay1.FontObjects.Name.BoxWidth = square + ((padding + frame) * 2);
theme.DoubleDisplay1.FontObjects.Name.BoxHeight = fontHeight;
theme.DoubleDisplay1.FontObjects.Name.OffsetX = 0;
theme.DoubleDisplay1.FontObjects.Name.OffsetY = (2 * frame) + square;
theme.DoubleDisplay1.FontObjects.Name.OutlineWidth = fontOutline;
theme.DoubleDisplay1.FontObjects.Name.FontHeight = fontSize;
theme.DoubleDisplay1.FontObjects.Name.FontFamily = 'Arial';
theme.DoubleDisplay1.FontObjects.Name.FontFlags = 0;
theme.DoubleDisplay1.FontObjects.Name.FontAlignment = 1;
theme.DoubleDisplay1.FontObjects.Name.FontColor = 0xFFFFFFFF;
theme.DoubleDisplay1.FontObjects.Name.OutlineColor = 0xFF000000;
theme.DoubleDisplay1.FontObjects.Recast = {};
theme.DoubleDisplay1.FontObjects.Recast.BoxWidth = square;
theme.DoubleDisplay1.FontObjects.Recast.BoxHeight = fontHeight;
theme.DoubleDisplay1.FontObjects.Recast.OffsetX = padding + frame;
theme.DoubleDisplay1.FontObjects.Recast.OffsetY = (frame + square) - fontHeight;
theme.DoubleDisplay1.FontObjects.Recast.OutlineWidth = fontOutline;
theme.DoubleDisplay1.FontObjects.Recast.FontHeight = fontSize;
theme.DoubleDisplay1.FontObjects.Recast.FontFamily = 'Arial';
theme.DoubleDisplay1.FontObjects.Recast.FontFlags = 0;
theme.DoubleDisplay1.FontObjects.Recast.FontAlignment = 0;
theme.DoubleDisplay1.FontObjects.Recast.FontColor = 0xFF389609;
theme.DoubleDisplay1.FontObjects.Recast.OutlineColor = 0xFF000000;
theme.DoubleDisplay1.ImageObjects = {};
theme.DoubleDisplay1.ImageObjects.Frame = {};
theme.DoubleDisplay1.ImageObjects.Frame.OffsetX = padding;
theme.DoubleDisplay1.ImageObjects.Frame.OffsetY = 0;
theme.DoubleDisplay1.ImageObjects.Frame.Width = square + (2 * frame);
theme.DoubleDisplay1.ImageObjects.Frame.Height = square + (2 * frame);
theme.DoubleDisplay1.ImageObjects.Icon = {};
theme.DoubleDisplay1.ImageObjects.Icon.OffsetX = padding + frame;
theme.DoubleDisplay1.ImageObjects.Icon.OffsetY = frame;
theme.DoubleDisplay1.ImageObjects.Icon.Width = square;
theme.DoubleDisplay1.ImageObjects.Icon.Height = square;
theme.DoubleDisplay1.ImageObjects.Overlay = {};
theme.DoubleDisplay1.ImageObjects.Overlay.OffsetX = padding + frame;
theme.DoubleDisplay1.ImageObjects.Overlay.OffsetY = frame;
theme.DoubleDisplay1.ImageObjects.Overlay.Width = square;
theme.DoubleDisplay1.ImageObjects.Overlay.Height = square;
theme.DoubleDisplay1.Primitives = T{};
theme.DoubleDisplay1.FramePath = 'misc/frame.png';
theme.DoubleDisplay1.PanelHeight = panelHeight;
theme.DoubleDisplay1.PanelWidth = (12 * objWidth) + (5 * spacing) + 16;
theme.DoubleDisplay1.DefaultX = 0;
theme.DoubleDisplay1.DefaultY = 0;
theme.DoubleDisplay1.SquareHeight = objHeight;
theme.DoubleDisplay1.SquareWidth = objWidth;
theme.DoubleDisplay1.Squares = T{};
theme.DoubleDisplay1.Squares[1] = { OffsetX = objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay1.Squares[2] = { OffsetX = (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay1.Squares[3] = { OffsetX = objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay1.Squares[4] = { OffsetX = 0, OffsetY = verticalOffset1 };
offset = (objWidth * 3) + 4 + spacing;
theme.DoubleDisplay1.Squares[5] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay1.Squares[6] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay1.Squares[7] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay1.Squares[8] = { OffsetX = offset, OffsetY = verticalOffset1 };
offset = offset + (3 * objWidth) + 4 + (3 * spacing);
theme.DoubleDisplay1.Squares[9] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay1.Squares[10] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay1.Squares[11] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay1.Squares[12] = { OffsetX = offset, OffsetY = verticalOffset1 };
offset = offset + (3 * objWidth) + 4 + spacing;
theme.DoubleDisplay1.Squares[13] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay1.Squares[14] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay1.Squares[15] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay1.Squares[16] = { OffsetX = offset, OffsetY = verticalOffset1 };
theme.DoubleDisplay2 = {};
theme.DoubleDisplay2.FontObjects = {};
theme.DoubleDisplay2.FontObjects.Cost = {};
theme.DoubleDisplay2.FontObjects.Cost.BoxWidth = square;
theme.DoubleDisplay2.FontObjects.Cost.BoxHeight = fontHeight;
theme.DoubleDisplay2.FontObjects.Cost.OffsetX = padding + frame;
theme.DoubleDisplay2.FontObjects.Cost.OffsetY = (frame + square) - fontHeight;
theme.DoubleDisplay2.FontObjects.Cost.OutlineWidth = fontOutline;
theme.DoubleDisplay2.FontObjects.Cost.FontHeight = fontSize;
theme.DoubleDisplay2.FontObjects.Cost.FontFamily = 'Arial';
theme.DoubleDisplay2.FontObjects.Cost.FontFlags = 0;
theme.DoubleDisplay2.FontObjects.Cost.FontAlignment = 2;
theme.DoubleDisplay2.FontObjects.Cost.FontColor = 0xFF389609;
theme.DoubleDisplay2.FontObjects.Cost.OutlineColor = 0xFF000000;
theme.DoubleDisplay2.FontObjects.Macro = {};
theme.DoubleDisplay2.FontObjects.Macro.BoxWidth = square;
theme.DoubleDisplay2.FontObjects.Macro.BoxHeight = fontHeight;
theme.DoubleDisplay2.FontObjects.Macro.OffsetX = padding + frame;
theme.DoubleDisplay2.FontObjects.Macro.OffsetY = frame;
theme.DoubleDisplay2.FontObjects.Macro.OutlineWidth = fontOutline;
theme.DoubleDisplay2.FontObjects.Macro.FontHeight = fontSize;
theme.DoubleDisplay2.FontObjects.Macro.FontFamily = 'Arial';
theme.DoubleDisplay2.FontObjects.Macro.FontFlags = 0;
theme.DoubleDisplay2.FontObjects.Macro.FontAlignment = 0;
theme.DoubleDisplay2.FontObjects.Macro.FontColor = 0xFFFFFFFF;
theme.DoubleDisplay2.FontObjects.Macro.OutlineColor = 0xFF000000;
theme.DoubleDisplay2.FontObjects.Name = {};
theme.DoubleDisplay2.FontObjects.Name.BoxWidth = square + ((padding + frame) * 2);
theme.DoubleDisplay2.FontObjects.Name.BoxHeight = fontHeight;
theme.DoubleDisplay2.FontObjects.Name.OffsetX = 0;
theme.DoubleDisplay2.FontObjects.Name.OffsetY = (2 * frame) + square;
theme.DoubleDisplay2.FontObjects.Name.OutlineWidth = fontOutline;
theme.DoubleDisplay2.FontObjects.Name.FontHeight = fontSize;
theme.DoubleDisplay2.FontObjects.Name.FontFamily = 'Arial';
theme.DoubleDisplay2.FontObjects.Name.FontFlags = 0;
theme.DoubleDisplay2.FontObjects.Name.FontAlignment = 1;
theme.DoubleDisplay2.FontObjects.Name.FontColor = 0xFFFFFFFF;
theme.DoubleDisplay2.FontObjects.Name.OutlineColor = 0xFF000000;
theme.DoubleDisplay2.FontObjects.Recast = {};
theme.DoubleDisplay2.FontObjects.Recast.BoxWidth = square;
theme.DoubleDisplay2.FontObjects.Recast.BoxHeight = fontHeight;
theme.DoubleDisplay2.FontObjects.Recast.OffsetX = padding + frame;
theme.DoubleDisplay2.FontObjects.Recast.OffsetY = (frame + square) - fontHeight;
theme.DoubleDisplay2.FontObjects.Recast.OutlineWidth = fontOutline;
theme.DoubleDisplay2.FontObjects.Recast.FontHeight = fontSize;
theme.DoubleDisplay2.FontObjects.Recast.FontFamily = 'Arial';
theme.DoubleDisplay2.FontObjects.Recast.FontFlags = 0;
theme.DoubleDisplay2.FontObjects.Recast.FontAlignment = 0;
theme.DoubleDisplay2.FontObjects.Recast.FontColor = 0xFF389609;
theme.DoubleDisplay2.FontObjects.Recast.OutlineColor = 0xFF000000;
theme.DoubleDisplay2.ImageObjects = {};
theme.DoubleDisplay2.ImageObjects.Frame = {};
theme.DoubleDisplay2.ImageObjects.Frame.OffsetX = padding;
theme.DoubleDisplay2.ImageObjects.Frame.OffsetY = 0;
theme.DoubleDisplay2.ImageObjects.Frame.Width = square + (2 * frame);
theme.DoubleDisplay2.ImageObjects.Frame.Height = square + (2 * frame);
theme.DoubleDisplay2.ImageObjects.Icon = {};
theme.DoubleDisplay2.ImageObjects.Icon.OffsetX = padding + frame;
theme.DoubleDisplay2.ImageObjects.Icon.OffsetY = frame;
theme.DoubleDisplay2.ImageObjects.Icon.Width = square;
theme.DoubleDisplay2.ImageObjects.Icon.Height = square;
theme.DoubleDisplay2.ImageObjects.Overlay = {};
theme.DoubleDisplay2.ImageObjects.Overlay.OffsetX = padding + frame;
theme.DoubleDisplay2.ImageObjects.Overlay.OffsetY = frame;
theme.DoubleDisplay2.ImageObjects.Overlay.Width = square;
theme.DoubleDisplay2.ImageObjects.Overlay.Height = square;
theme.DoubleDisplay2.Primitives = T{};
theme.DoubleDisplay2.FramePath = 'misc/frame.png';
theme.DoubleDisplay2.PanelHeight = panelHeight;
theme.DoubleDisplay2.PanelWidth = (12 * objWidth) + (5 * spacing) + 16;
theme.DoubleDisplay2.DefaultX = 0;
theme.DoubleDisplay2.DefaultY = 0;
theme.DoubleDisplay2.SquareHeight = objHeight;
theme.DoubleDisplay2.SquareWidth = objWidth;
theme.DoubleDisplay2.Squares = T{};
theme.DoubleDisplay2.Squares[1] = { OffsetX = objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay2.Squares[2] = { OffsetX = (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay2.Squares[3] = { OffsetX = objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay2.Squares[4] = { OffsetX = 0, OffsetY = verticalOffset1 };
offset = (objWidth * 3) + 4 + spacing;
theme.DoubleDisplay2.Squares[5] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay2.Squares[6] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay2.Squares[7] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay2.Squares[8] = { OffsetX = offset, OffsetY = verticalOffset1 };
offset = offset + (3 * objWidth) + 4 + (3 * spacing);
theme.DoubleDisplay2.Squares[9] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay2.Squares[10] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay2.Squares[11] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay2.Squares[12] = { OffsetX = offset, OffsetY = verticalOffset1 };
offset = offset + (3 * objWidth) + 4 + spacing;
theme.DoubleDisplay2.Squares[13] = { OffsetX = offset + objWidth + 2, OffsetY = 0 };
theme.DoubleDisplay2.Squares[14] = { OffsetX = offset + (2 * objWidth) + 4, OffsetY = verticalOffset1 };
theme.DoubleDisplay2.Squares[15] = { OffsetX = offset + objWidth + 2, OffsetY = verticalOffset2 };
theme.DoubleDisplay2.Squares[16] = { OffsetX = offset, OffsetY = verticalOffset1 };

local scaling = require('scaling');
if ((scaling.window.w == -1) or (scaling.window.h == -1) or (scaling.menu.w == -1) or (scaling.menu.h == -1)) then
    theme.SingleDisplay1.DefaultX = 0;
    theme.SingleDisplay1.DefaultY = 0;
    theme.DoubleDisplay1.DefaultX = 0;
    theme.DoubleDisplay1.DefaultY = 0;
    theme.SingleDisplay2.DefaultX = 0;
    theme.SingleDisplay2.DefaultY = 0;
    theme.DoubleDisplay2.DefaultX = 0;
    theme.DoubleDisplay2.DefaultY = 0;
else
    theme.SingleDisplay1.DefaultX = (scaling.window.w - theme.SingleDisplay1.PanelWidth) / 2;
    theme.SingleDisplay1.DefaultY = scaling.window.h - (scaling.scale_height(150) + theme.SingleDisplay1.PanelHeight);
    theme.DoubleDisplay1.DefaultX = (scaling.window.w - theme.DoubleDisplay1.PanelWidth) / 2;
    theme.DoubleDisplay1.DefaultY = scaling.window.h - (scaling.scale_height(150) + theme.DoubleDisplay1.PanelHeight);
    theme.SingleDisplay2.DefaultX = (scaling.window.w - theme.SingleDisplay1.PanelWidth) / 2;
    theme.SingleDisplay2.DefaultY = scaling.window.h - (scaling.scale_height(150) + 2*theme.SingleDisplay1.PanelHeight);
    theme.DoubleDisplay2.DefaultX = (scaling.window.w - theme.DoubleDisplay1.PanelWidth) / 2;
    theme.DoubleDisplay2.DefaultY = scaling.window.h - (scaling.scale_height(150) + 2*theme.DoubleDisplay1.PanelHeight);
end

return theme;